services:
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - data:/storage
    depends_on:
     - redis
  celery: 
    build: .
    restart: always
    volumes:
      - data:/storage
    entrypoint: celery -A tasks worker -l Info -P eventlet
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - data:/storage

volumes:
  data: